version: '3'
services:
   mysql-service:
     image: zldev/mysql:1.0.0-alpha
     restart: always
     container_name: mysql-kanj
     volumes:
     - /opt/fp/mysql:/var/lib/mysql/
     ports:
     - "3320:3306"
     environment:
       MYSQL_USER: root
       MYSQL_ROOT_PASSWORD: mysql

